import type { Metadata } from "next";

import "./globals.css";
import { Header } from "@/shared/ui";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="w-full">
          <Header />
          <main className="max-w-[960px] w-full mx-auto pt-20">{children}</main>
        </div>
      </body>
    </html>
  );
}
